import { ProjectOverview } from "../types";

export function renderProjectOverview(overview: ProjectOverview): string {
	const lines: string[] = [];

	lines.push("# Project Overview");
	lines.push("");

	// Basic Information
	lines.push("## Basic Information");
	lines.push("");
	lines.push(`**Name:** ${overview.projectName || "Unknown"}`);
	lines.push(`**Type:** ${overview.projectType || "Unknown"}`);
	lines.push(`**Primary Language:** ${overview.primaryLanguage || "Unknown"}`);
	lines.push("");

	// Frameworks
	lines.push("## Frameworks & Libraries");
	lines.push("");
	if (overview.frameworks.length > 0) {
		overview.frameworks.forEach(framework => {
			lines.push(`- ${framework}`);
		});
	} else {
		lines.push("None detected");
	}
	lines.push("");

	// Entry Points
	lines.push("## Entry Points");
	lines.push("");
	if (overview.entryPoints.length > 0) {
		overview.entryPoints.forEach(entry => {
			lines.push(`- \`${entry}\``);
		});
	} else {
		lines.push("None detected");
	}
	lines.push("");

	// Project Structure
	lines.push("## Project Structure");
	lines.push("");
	if (overview.structureSummary.length > 0) {
		overview.structureSummary.forEach(dir => {
			lines.push(`- \`${dir}/\``);
		});
	} else {
		lines.push("No directories detected");
	}
	lines.push("");

	// Dependencies
	if (overview.dependencies.length > 0) {
		lines.push("## Dependencies");
		lines.push("");
		overview.dependencies.forEach(dep => {
			lines.push(`- ${dep}`);
		});
		lines.push("");
	}

	// Dev Dependencies
	if (overview.devDependencies.length > 0) {
		lines.push("## Development Dependencies");
		lines.push("");
		overview.devDependencies.forEach(dep => {
			lines.push(`- ${dep}`);
		});
		lines.push("");
	}

	// Notes
	if (overview.notes.length > 0) {
		lines.push("## Notes");
		lines.push("");
		overview.notes.forEach(note => {
			lines.push(`- ${note}`);
		});
		lines.push("");
	}

	lines.push("---");
	lines.push(`*Generated by Explain This Project extension on ${new Date().toISOString()}*`);

	return lines.join("\n");
}
